import json
from pathlib import Path
from typing import Dict, Any, List

# Importing your specific generator class
from api_testing.data_generator.heuristic_data_generator.HeuristicGenerator import HeuristicDataGenerator

def test_generation_for_all_endpoints(json_path: str):
    """
    Iterates through every endpoint in the blueprint and generates data
    only for heuristic-enabled fields.
    """
    # 1. Initialize the Generator with a seed for consistency
    generator = HeuristicDataGenerator(seed=123)
    
    # 2. Load the JSON Blueprint (contains all endpoints)
    print(f"[*] Loading configuration from: {json_path}")
    if not Path(json_path).exists():
        print(f"[!] File not found: {json_path}")
        return {}

    with open(json_path, "r", encoding="utf-8") as f:
        blueprints = json.load(f)

    all_test_data = {}

    # 3. Process every endpoint in the list
    for entry in blueprints:
        # Use the identifier (e.g., 'get-/projects')
        endpoint_id = entry.get("endpoint_id")
        
        generated_entry = {
            "params": {},
            "body": {}
        }

        # --- Process Parameters ---
        for p in entry.get("params", []):
            name = p["name"]
            conf = p["config"]
            
            # Rule: Only generate if function is defined. 
            # If config is {} or function is "", it is skipped.
            if conf and conf.get("function"):
                val = generator.generate_value_by_rule(conf["function"], conf["arguments"])
                generated_entry["params"][name] = val

        # --- Process Body ---
        for b in entry.get("body", []):
            name = b["name"]
            conf = b["config"]
            
            if conf and conf.get("function"):
                val = generator.generate_value_by_rule(conf["function"], conf["arguments"])
                generated_entry["body"][name] = val

        # --- Output Filtering ---
        # Only add to the final JSON if there is at least one heuristic field generated
        if generated_entry["params"] or generated_entry["body"]:
            all_test_data[endpoint_id] = generated_entry

    return all_test_data

if __name__ == "__main__":
    # Path to the blueprint generated by DataConfigManager
    CONFIG_FILE = "Test/gitlab_blueprint.json"
    OUTPUT_FILE = "test/executed_test_values.json"
    
    # Ensure output directory exists
    Path(OUTPUT_FILE).parent.mkdir(parents=True, exist_ok=True)

    results = test_generation_for_all_endpoints(CONFIG_FILE)
    
    if results:
        # 4. Save only the generated values
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=4)
            
        print(f"\n[Done] Processed all endpoints.")
        print(f"[+] Total endpoints with heuristic data: {len(results)}")
        print(f"[+] Results saved to: {OUTPUT_FILE}")
    else:
        print("\n[!] No heuristic data was generated. All fields may be marked for LLM.")