import {
  useGetDynamicConstraintsApiV1RunsRunNameConstraintsDynamicGet,
  useGetStaticConstraintsApiV1RunsRunNameConstraintsStaticGet,
  useListDynamicConstraintEntriesApiV1RunsRunNameConstraintsDynamicEntriesGet,
  useListDynamicInvariantsApiV1RunsRunNameConstraintsDynamicInvariantsGet,
  useListStaticConstraintEntriesApiV1RunsRunNameConstraintsStaticEntriesGet,
} from '../../shared/api/generated/constraints/constraints'

export const useStaticConstraintsSummary = useGetStaticConstraintsApiV1RunsRunNameConstraintsStaticGet
export const useStaticConstraintEntries = useListStaticConstraintEntriesApiV1RunsRunNameConstraintsStaticEntriesGet
export const useDynamicConstraintsSummary = useGetDynamicConstraintsApiV1RunsRunNameConstraintsDynamicGet
export const useDynamicConstraintEntries = useListDynamicConstraintEntriesApiV1RunsRunNameConstraintsDynamicEntriesGet
export const useDynamicInvariants = useListDynamicInvariantsApiV1RunsRunNameConstraintsDynamicInvariantsGet
