from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from api_testing.backend.api.errors import register_exception_handlers
from api_testing.backend.api.routers import (
    artifacts,
    constraints,
    dependency_graph,
    executions,
    health,
    history,
    operations,
    reports,
    run_configs,
    runs,
    specs,
    test_cases,
)
from api_testing.backend.application.services import ArtifactQueryService
from api_testing.backend.application.review_services.combination_review import (
    CombinationReviewService,
)
from api_testing.backend.application.research_services.constraint_research import (
    ConstraintResearchService,
)
from api_testing.backend.application.write_services import WriteFlowService
from api_testing.backend.infrastructure.artifacts.repository import FileArtifactRepository
from api_testing.backend.infrastructure.combination_review_metadata import (
    SQLiteCombinationReviewRepository,
)
from api_testing.backend.infrastructure.execution_runner import HybridExecutionRunner
from api_testing.backend.infrastructure.spec_storage import FileSpecStorage
from api_testing.backend.infrastructure.write_metadata import SQLiteWriteMetadataRepository
from api_testing.backend.settings import BackendSettings


OPENAPI_TAGS = [
    {
        "name": "health",
        "description": "Readiness signal for the artifact backend process.",
    },
    {
        "name": "runs",
        "description": "Local APIPilot cache run catalog and run-level summaries.",
    },
    {
        "name": "artifacts",
        "description": "Typed artifact metadata, summaries, and sanitized raw content.",
    },
    {
        "name": "operations",
        "description": "Operation read models derived from normalized OpenAPI artifacts.",
    },
    {
        "name": "reports",
        "description": "Status-code report buckets generated by APIPilot runs.",
    },
    {
        "name": "graph",
        "description": "Operation dependency graph nodes, edges, and similarity evidence.",
    },
    {
        "name": "constraints",
        "description": "Static and dynamic constraint read models for oracle inspection.",
    },
    {
        "name": "test-cases",
        "description": "Pageable, body-safe test case records.",
    },
    {
        "name": "history",
        "description": "HAR session summaries and sanitized execution history entries.",
    },
    {
        "name": "specs",
        "description": "Uploaded OpenAPI specifications and operation previews.",
    },
    {
        "name": "run-configs",
        "description": "Validated APIPilot run configurations with redacted secrets.",
    },
    {
        "name": "executions",
        "description": "Write-flow execution lifecycle, events, and run mapping.",
    },
]


def create_app(settings: BackendSettings | None = None) -> FastAPI:
    app_settings = settings or BackendSettings.from_env()
    repository = FileArtifactRepository(app_settings.cache_root)
    write_repository = SQLiteWriteMetadataRepository(app_settings.metadata_db_path)
    review_repository = SQLiteCombinationReviewRepository(app_settings.metadata_db_path)
    service = ArtifactQueryService(repository, review_repository)
    write_repository.reconcile_orphaned_executions(reason="worker_orphaned")
    spec_storage = FileSpecStorage(app_settings.spec_storage_root)
    execution_runner = HybridExecutionRunner(
        write_repository,
        spec_storage,
        app_settings,
    )
    write_service = WriteFlowService(
        write_repository,
        spec_storage,
        execution_runner,
        allowed_target_base_urls=app_settings.allowed_target_base_urls,
        max_active_executions=app_settings.max_active_executions,
    )
    combination_review_service = CombinationReviewService(
        service,
        review_repository,
        app_settings,
    )
    constraint_research_service = ConstraintResearchService(
        service,
        app_settings.cache_root,
    )

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        try:
            yield
        finally:
            execution_runner.shutdown()

    app = FastAPI(
        title="APIPilot Artifact Backend",
        version="0.1.0",
        description=(
            "HTTP API for APIPilot local cache artifacts and local write-flow "
            "orchestration."
        ),
        openapi_tags=OPENAPI_TAGS,
        lifespan=lifespan,
    )
    app.state.settings = app_settings
    app.state.artifact_service = service
    app.state.write_flow_service = write_service
    app.state.combination_review_service = combination_review_service
    app.state.constraint_research_service = constraint_research_service

    if app_settings.allowed_origins:
        app.add_middleware(
            CORSMiddleware,
            allow_origins=list(app_settings.allowed_origins),
            allow_credentials=False,
            allow_methods=["GET", "POST", "PUT"],
            allow_headers=["*"],
        )

    register_exception_handlers(app)
    app.include_router(health.router)
    app.include_router(runs.router)
    app.include_router(artifacts.router)
    app.include_router(operations.router)
    app.include_router(reports.router)
    app.include_router(dependency_graph.router)
    app.include_router(constraints.router)
    app.include_router(test_cases.router)
    app.include_router(history.router)
    app.include_router(specs.router)
    app.include_router(run_configs.router)
    app.include_router(executions.router)

    return app


app = create_app()
