from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from api_testing.backend.api.errors import register_exception_handlers
from api_testing.backend.api.routers import (
    artifacts,
    constraints,
    dependency_graph,
    health,
    history,
    operations,
    reports,
    runs,
    test_cases,
)
from api_testing.backend.application.services import ArtifactQueryService
from api_testing.backend.infrastructure.artifacts.repository import FileArtifactRepository
from api_testing.backend.settings import BackendSettings


OPENAPI_TAGS = [
    {
        "name": "health",
        "description": "Readiness signal for the artifact backend process.",
    },
    {
        "name": "runs",
        "description": "Local APIPilot cache run catalog and run-level summaries.",
    },
    {
        "name": "artifacts",
        "description": "Typed artifact metadata, summaries, and sanitized raw content.",
    },
    {
        "name": "operations",
        "description": "Operation read models derived from normalized OpenAPI artifacts.",
    },
    {
        "name": "reports",
        "description": "Status-code report buckets generated by APIPilot runs.",
    },
    {
        "name": "graph",
        "description": "Operation dependency graph nodes, edges, and similarity evidence.",
    },
    {
        "name": "constraints",
        "description": "Static and dynamic constraint read models for oracle inspection.",
    },
    {
        "name": "test-cases",
        "description": "Pageable, body-safe test case records.",
    },
    {
        "name": "history",
        "description": "HAR session summaries and sanitized execution history entries.",
    },
]


def create_app(settings: BackendSettings | None = None) -> FastAPI:
    app_settings = settings or BackendSettings.from_env()
    repository = FileArtifactRepository(app_settings.cache_root)
    service = ArtifactQueryService(repository)

    app = FastAPI(
        title="APIPilot Artifact Backend",
        version="0.1.0",
        description="Read-only HTTP API for APIPilot local cache artifacts.",
        openapi_tags=OPENAPI_TAGS,
    )
    app.state.settings = app_settings
    app.state.artifact_service = service

    if app_settings.allowed_origins:
        app.add_middleware(
            CORSMiddleware,
            allow_origins=list(app_settings.allowed_origins),
            allow_credentials=False,
            allow_methods=["GET"],
            allow_headers=["*"],
        )

    register_exception_handlers(app)
    app.include_router(health.router)
    app.include_router(runs.router)
    app.include_router(artifacts.router)
    app.include_router(operations.router)
    app.include_router(reports.router)
    app.include_router(dependency_graph.router)
    app.include_router(constraints.router)
    app.include_router(test_cases.router)
    app.include_router(history.router)

    return app


app = create_app()
