from __future__ import annotations

from api_testing.backend.api.schemas import (
    ArtifactAvailabilityResponse,
    ArtifactCatalogResponse,
    ArtifactContentResponse,
    ArtifactMetadataResponse,
    ConstraintEntryResponse,
    ConstraintEntryDetailResponse,
    ConstraintEntryPageResponse,
    ConstraintExplorerDetailResponse,
    ConstraintExplorerEntryResponse,
    ConstraintExplorerPageResponse,
    ConstraintFacetBucketResponse,
    ConstraintFacetsResponse,
    ConstraintQueryMetadataResponse,
    ConstraintSectionResponse,
    DependencyGraphResponse,
    DynamicConstraintsResponse,
    ErrorDetail,
    ErrorResponse,
    GraphEdgeDetailResponse,
    GraphEdgePageResponse,
    GraphEdgeResponse,
    GraphEvidenceResponse,
    GraphExplorerEdgeResponse,
    GraphFacetBucketResponse,
    GraphFacetsResponse,
    GraphNodePageResponse,
    GraphNodeResponse,
    GraphSequencePageResponse,
    GraphSequenceParameterSourceResponse,
    GraphSequenceResponse,
    GraphSimilarityResponse,
    GroupCountResponse,
    HarEntryPageResponse,
    HarEntryResponse,
    HarSessionListResponse,
    HarSessionSummaryResponse,
    HealthResponse,
    InvariantDetailResponse,
    InvariantExplorerDetailResponse,
    InvariantExplorerEntryResponse,
    InvariantExplorerFacetsResponse,
    InvariantExplorerPageResponse,
    InvariantGroupResponse,
    InvariantPageResponse,
    InvariantRecordResponse,
    OperationDetailResponse,
    OperationExplorerDetailResponse,
    OperationExplorerEntryResponse,
    OperationExplorerPageResponse,
    OperationFacetBucketResponse,
    OperationFacetsResponse,
    OperationListResponse,
    OperationSummaryResponse,
    PaginationMetadata,
    ReportEntryPageResponse,
    ReportsResponse,
    RunCatalogResponse,
    RunMetadataResponse,
    RunSummaryResponse,
    SanitizedBodyResponse,
    StaticConstraintsResponse,
    StatusReportEntryResponse,
    TestCasePageResponse,
    TestCaseResponse,
)

ArtifactAvailability = ArtifactAvailabilityResponse
ArtifactMetadata = ArtifactMetadataResponse
GraphResponse = DependencyGraphResponse
HarEntryPage = HarEntryPageResponse
HarEntrySummary = HarEntryResponse
HarSessionSummary = HarSessionSummaryResponse
OperationDetail = OperationDetailResponse
OperationSummary = OperationSummaryResponse
RunMetadata = RunMetadataResponse
RunSummary = RunSummaryResponse
TestCasePage = TestCasePageResponse
TestCaseSummary = TestCaseResponse

__all__ = [
    "ArtifactAvailability",
    "ArtifactAvailabilityResponse",
    "ArtifactCatalogResponse",
    "ArtifactContentResponse",
    "ArtifactMetadata",
    "ArtifactMetadataResponse",
    "ConstraintEntryDetailResponse",
    "ConstraintEntryPageResponse",
    "ConstraintEntryResponse",
    "ConstraintExplorerDetailResponse",
    "ConstraintExplorerEntryResponse",
    "ConstraintExplorerPageResponse",
    "ConstraintFacetBucketResponse",
    "ConstraintFacetsResponse",
    "ConstraintQueryMetadataResponse",
    "ConstraintSectionResponse",
    "DependencyGraphResponse",
    "DynamicConstraintsResponse",
    "ErrorDetail",
    "ErrorResponse",
    "GraphEdgeDetailResponse",
    "GraphEdgeResponse",
    "GraphEdgePageResponse",
    "GraphEvidenceResponse",
    "GraphExplorerEdgeResponse",
    "GraphFacetBucketResponse",
    "GraphFacetsResponse",
    "GraphNodePageResponse",
    "GraphNodeResponse",
    "GraphResponse",
    "GraphSequencePageResponse",
    "GraphSequenceParameterSourceResponse",
    "GraphSequenceResponse",
    "GraphSimilarityResponse",
    "GroupCountResponse",
    "HarEntryPage",
    "HarEntryPageResponse",
    "HarEntryResponse",
    "HarEntrySummary",
    "HarSessionListResponse",
    "HarSessionSummary",
    "HarSessionSummaryResponse",
    "HealthResponse",
    "InvariantDetailResponse",
    "InvariantExplorerDetailResponse",
    "InvariantExplorerEntryResponse",
    "InvariantExplorerFacetsResponse",
    "InvariantExplorerPageResponse",
    "InvariantGroupResponse",
    "InvariantPageResponse",
    "InvariantRecordResponse",
    "OperationDetail",
    "OperationDetailResponse",
    "OperationExplorerDetailResponse",
    "OperationExplorerEntryResponse",
    "OperationExplorerPageResponse",
    "OperationFacetBucketResponse",
    "OperationFacetsResponse",
    "OperationListResponse",
    "OperationSummary",
    "OperationSummaryResponse",
    "PaginationMetadata",
    "ReportEntryPageResponse",
    "ReportsResponse",
    "RunCatalogResponse",
    "RunMetadata",
    "RunMetadataResponse",
    "RunSummary",
    "RunSummaryResponse",
    "SanitizedBodyResponse",
    "StaticConstraintsResponse",
    "StatusReportEntryResponse",
    "TestCasePage",
    "TestCasePageResponse",
    "TestCaseResponse",
    "TestCaseSummary",
]
