from __future__ import annotations

from api_testing.backend.api.schemas import (
    ArtifactAvailabilityResponse,
    ArtifactCatalogResponse,
    ArtifactContentResponse,
    ArtifactMetadataResponse,
    ConstraintEntryResponse,
    ConstraintEntryDetailResponse,
    ConstraintEntryPageResponse,
    ConstraintSectionResponse,
    DependencyGraphResponse,
    DynamicConstraintsResponse,
    ErrorDetail,
    ErrorResponse,
    GraphEdgePageResponse,
    GraphEdgeResponse,
    GraphSimilarityResponse,
    GroupCountResponse,
    HarEntryPageResponse,
    HarEntryResponse,
    HarSessionListResponse,
    HarSessionSummaryResponse,
    HealthResponse,
    InvariantDetailResponse,
    InvariantGroupResponse,
    InvariantPageResponse,
    InvariantRecordResponse,
    OperationDetailResponse,
    OperationListResponse,
    OperationSummaryResponse,
    PaginationMetadata,
    ReportEntryPageResponse,
    ReportsResponse,
    RunCatalogResponse,
    RunMetadataResponse,
    RunSummaryResponse,
    SanitizedBodyResponse,
    StaticConstraintsResponse,
    StatusReportEntryResponse,
    TestCasePageResponse,
    TestCaseResponse,
)

ArtifactAvailability = ArtifactAvailabilityResponse
ArtifactMetadata = ArtifactMetadataResponse
GraphResponse = DependencyGraphResponse
HarEntryPage = HarEntryPageResponse
HarEntrySummary = HarEntryResponse
HarSessionSummary = HarSessionSummaryResponse
OperationDetail = OperationDetailResponse
OperationSummary = OperationSummaryResponse
RunMetadata = RunMetadataResponse
RunSummary = RunSummaryResponse
TestCasePage = TestCasePageResponse
TestCaseSummary = TestCaseResponse

__all__ = [
    "ArtifactAvailability",
    "ArtifactAvailabilityResponse",
    "ArtifactCatalogResponse",
    "ArtifactContentResponse",
    "ArtifactMetadata",
    "ArtifactMetadataResponse",
    "ConstraintEntryDetailResponse",
    "ConstraintEntryPageResponse",
    "ConstraintEntryResponse",
    "ConstraintSectionResponse",
    "DependencyGraphResponse",
    "DynamicConstraintsResponse",
    "ErrorDetail",
    "ErrorResponse",
    "GraphEdgeResponse",
    "GraphEdgePageResponse",
    "GraphResponse",
    "GraphSimilarityResponse",
    "GroupCountResponse",
    "HarEntryPage",
    "HarEntryPageResponse",
    "HarEntryResponse",
    "HarEntrySummary",
    "HarSessionListResponse",
    "HarSessionSummary",
    "HarSessionSummaryResponse",
    "HealthResponse",
    "InvariantDetailResponse",
    "InvariantGroupResponse",
    "InvariantPageResponse",
    "InvariantRecordResponse",
    "OperationDetail",
    "OperationDetailResponse",
    "OperationListResponse",
    "OperationSummary",
    "OperationSummaryResponse",
    "PaginationMetadata",
    "ReportEntryPageResponse",
    "ReportsResponse",
    "RunCatalogResponse",
    "RunMetadata",
    "RunMetadataResponse",
    "RunSummary",
    "RunSummaryResponse",
    "SanitizedBodyResponse",
    "StaticConstraintsResponse",
    "StatusReportEntryResponse",
    "TestCasePage",
    "TestCasePageResponse",
    "TestCaseResponse",
    "TestCaseSummary",
]
