import type { TourAnchorId } from './productTourTypes'

export const TOUR_ANCHORS = {
  appBackendHealth: 'app-backend-health',
  appDensityControl: 'app-density-control',
  appHelp: 'app-help',
  appRunContext: 'app-run-context',
  appSidebar: 'app-sidebar',
  artifactsCatalog: 'artifacts-catalog',
  artifactsDetail: 'artifacts-detail',
  artifactsHeader: 'artifacts-header',
  builderExecutionHeader: 'builder-execution-header',
  builderExecutionSummary: 'builder-execution-summary',
  builderExecutionTimeline: 'builder-execution-timeline',
  builderExecutionsFilters: 'builder-executions-filters',
  builderExecutionsHeader: 'builder-executions-header',
  builderExecutionsTable: 'builder-executions-table',
  builderRunConfigActions: 'builder-run-config-actions',
  builderRunConfigFields: 'builder-run-config-fields',
  builderRunConfigHeader: 'builder-run-config-header',
  builderRunConfigStepper: 'builder-run-config-stepper',
  builderRunConfigSummary: 'builder-run-config-summary',
  builderSpecDetailHeader: 'builder-spec-detail-header',
  builderSpecOperations: 'builder-spec-operations',
  builderSpecsCatalog: 'builder-specs-catalog',
  builderSpecsHeader: 'builder-specs-header',
  builderSpecsUpload: 'builder-specs-upload',
  compareContentDiff: 'compare-content-diff',
  compareContentPanels: 'compare-content-panels',
  compareHeader: 'compare-header',
  compareMetadataDiff: 'compare-metadata-diff',
  compareSelectors: 'compare-selectors',
  constraintsDetail: 'constraints-detail',
  constraintsFilters: 'constraints-filters',
  constraintsHeader: 'constraints-header',
  constraintsLearningPanel: 'constraints-learning-panel',
  constraintsMatrix: 'constraints-matrix',
  constraintsWorkbench: 'constraints-workbench',
  graphControls: 'graph-controls',
  graphHeader: 'graph-header',
  graphInspector: 'graph-inspector',
  graphResults: 'graph-results',
  historyDetail: 'history-detail',
  historyHeader: 'history-header',
  historyResults: 'history-results',
  historySessions: 'history-sessions',
  operationsDetail: 'operations-detail',
  operationsFilters: 'operations-filters',
  operationsHeader: 'operations-header',
  operationsResults: 'operations-results',
  overviewHeader: 'overview-header',
  overviewHealthSignals: 'overview-health-signals',
  overviewNextInspection: 'overview-next-inspection',
  reportsHeader: 'reports-header',
  reportsResults: 'reports-results',
  reportsStatusDistribution: 'reports-status-distribution',
  runsCatalog: 'runs-catalog',
  runsHeader: 'runs-header',
  testCasesDetail: 'test-cases-detail',
  testCasesHeader: 'test-cases-header',
  testCasesResults: 'test-cases-results',
  onboardingPaths: 'onboarding-paths',
  workspaceEvidenceTray: 'workspace-evidence-tray',
  workspaceGraphFocus: 'workspace-graph-focus',
  workspaceHeader: 'workspace-header',
  workspaceInspector: 'workspace-inspector',
  workspaceOperations: 'workspace-operations',
} as const satisfies Record<string, TourAnchorId>

export function tourAnchor(anchorId: TourAnchorId) {
  return { 'data-tour-anchor': anchorId }
}
